version: "3.8"

services:
  RGRTRASPORTE:
    image: rgrtransporte:latest
    build:
      context: .
      dockerfile: RGRTRASPORTE/Dockerfile
    ports:
      - "4000:8080"
      - "4001:8081"
    container_name: rgrtransporte
    restart: unless-stopped
    depends_on:
      - postgres

  # plataforma-jobs:
  #   image: plataforma-jobs:latest
  #   build:
  #     context: .
  #     dockerfile: Jobs/Dockerfile
  #   ports:
  #     - "4100:8080"
  #     - "4101:8081"
  #   container_name: Jobs
  #   restart: unless-stopped
  #   depends_on:
  #     - mongo

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: S3cureP@ssw0rd!2024
      POSTGRES_DB: rgrtransporte
  
volumes:
  postgres_data:
