// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Data.Migrations.Transportador
{
    [DbContext(typeof(TransportadorContext))]
    [Migration("20250531225539_T000001")]
    partial class T000001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.Auditoria.HistoricoObjeto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("HOB_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Acao")
                        .HasColumnType("integer")
                        .HasColumnName("HOB_ACAO");

                    b.Property<long>("CodigoObjeto")
                        .HasColumnType("bigint")
                        .HasColumnName("HOB_CODIGO_OBJETO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("HOB_CREATED_AT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("HOB_DATA");

                    b.Property<string>("DescricaoAcao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("HOB_DESCRICAO_ACAO");

                    b.Property<string>("DescricaoObjeto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("HOB_DESCRICAO_OBJETO");

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("HOB_IP");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("HOB_OBJETO");

                    b.Property<int>("OrigemAuditado")
                        .HasColumnType("integer")
                        .HasColumnName("HOB_ORIGEM_AUDITADO");

                    b.Property<int>("TipoAuditado")
                        .HasColumnType("integer")
                        .HasColumnName("HOB_TIPO_AUDITADO");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("HOB_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("T_HISTORICO_OBJETO", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Auditoria.HistoricoPropriedade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("HPR_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("HPR_CREATED_AT");

                    b.Property<string>("De")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("HPR_DE");

                    b.Property<long>("HistoricoObjetoId")
                        .HasColumnType("bigint")
                        .HasColumnName("HOB_ID");

                    b.Property<string>("Para")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("HPR_PARA");

                    b.Property<string>("Propriedade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("HPR_PROPRIEDADE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("HPR_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("HistoricoObjetoId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("T_HISTORICO_PROPRIEDADE", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Localidades.Localidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Localidade");
                });

            modelBuilder.Entity("Dominio.Entidades.Pessoas.Motorista", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CNH")
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<int>("CategoriaCNH")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long>("LocalidadeDesembarqueId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocalidadeEmbarqueId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocalidadeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("RG")
                        .HasColumnType("text");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<bool>("Situacao")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidadeCNH")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Motorista");
                });

            modelBuilder.Entity("Dominio.Entidades.Pessoas.Passageiros.Passageiro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long?>("LocalidadeDesembarqueId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LocalidadeEmbarqueId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocalidadeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<bool>("Situacao")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadeDesembarqueId");

                    b.HasIndex("LocalidadeEmbarqueId");

                    b.HasIndex("LocalidadeId");

                    b.ToTable("Passageiro");
                });

            modelBuilder.Entity("Dominio.Entidades.Veiculos.ModeloVeicular", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MOV_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("MOV_CAPACIDADE_MAXIMA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MOV_CREATED_AT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MOV_DESCRICAO_MODELO");

                    b.Property<int>("PassageirosEmPe")
                        .HasColumnType("integer")
                        .HasColumnName("MOV_PASSAGEIROS_EM_PE");

                    b.Property<bool>("PossuiBanheiro")
                        .HasColumnType("boolean")
                        .HasColumnName("MOV_POSSUI_BANHEIRO");

                    b.Property<bool>("PossuiClimatizador")
                        .HasColumnType("boolean")
                        .HasColumnName("MOV_POSSUI_CLIMATIZADOR");

                    b.Property<int>("QuantidadeAssento")
                        .HasColumnType("integer")
                        .HasColumnName("MOV_QUANTIDADE_ASSENTO");

                    b.Property<int>("QuantidadeEixo")
                        .HasColumnType("integer")
                        .HasColumnName("MOV_QUANTIDADE_EIXO");

                    b.Property<bool>("Situacao")
                        .HasColumnType("boolean")
                        .HasColumnName("MOV_SITUACAO");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("MOV_TIPO");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MOV_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("T_MODELO_VEICULAR", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Veiculos.Veiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VEI_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("integer")
                        .HasColumnName("VEI_ANO_FABRICACAO");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("integer")
                        .HasColumnName("VEI_ANO_MODELO");

                    b.Property<string>("Cor")
                        .HasColumnType("text")
                        .HasColumnName("VEI_COR");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VEI_CREATED_AT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VEI_MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VEI_MODELO");

                    b.Property<long?>("ModeloVeiculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("MOV_ID");

                    b.Property<string>("NumeroChassi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VEI_NUMERO_CHASSI");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("VEI_OBSERVACAO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VEI_PLACA");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VEI_RENAVAM");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("VEI_STATUS");

                    b.Property<int>("TipoCombustivel")
                        .HasColumnType("integer")
                        .HasColumnName("VEI_TIPO_COMBUSTIVEL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VEI_UPDATED_AT");

                    b.Property<DateTime?>("VencimentoLicenciamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VEI_VENCIMENTO_LICENCIAMENTO");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ModeloVeiculoId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("T_VEICULO", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Viagens.Gatilho.GatilhoViagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("GAV_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("GAV_ATIVO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GAV_CREATED_AT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("GAV_DESCRICAO");

                    b.Property<string>("DescricaoViagem")
                        .HasColumnType("text")
                        .HasColumnName("GAV_DESCRICAO_VIAGEM");

                    b.Property<string>("DiasSemana")
                        .HasColumnType("text")
                        .HasColumnName("GAV_DIAS_SEMANA");

                    b.Property<decimal>("Distancia")
                        .HasColumnType("numeric")
                        .HasColumnName("GAV_DISTANCIA");

                    b.Property<TimeSpan>("HorarioChegada")
                        .HasColumnType("interval")
                        .HasColumnName("GAV_HORARIO_CHEGADA");

                    b.Property<TimeSpan>("HorarioSaida")
                        .HasColumnType("interval")
                        .HasColumnName("GAV_HORARIO_SAIDA");

                    b.Property<long>("LocalidadeDestinoId")
                        .HasColumnType("bigint")
                        .HasColumnName("LOC_DESTINO_ID");

                    b.Property<long>("LocalidadeOrigemId")
                        .HasColumnType("bigint")
                        .HasColumnName("LOC_ORIGEM_ID");

                    b.Property<long>("MotoristaId")
                        .HasColumnType("bigint")
                        .HasColumnName("MOT_MOTORISTA_ID");

                    b.Property<string>("PolilinhaRota")
                        .HasColumnType("text")
                        .HasColumnName("GAV_POLILINHA_ROTA");

                    b.Property<int>("QuantidadeVagas")
                        .HasColumnType("integer")
                        .HasColumnName("GAV_QUANTIDADE_VAGAS");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GAV_UPDATED_AT");

                    b.Property<decimal>("ValorPassagem")
                        .HasColumnType("numeric")
                        .HasColumnName("GAV_VALOR_PASSAGEM");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("VEI_ID");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LocalidadeDestinoId");

                    b.HasIndex("LocalidadeOrigemId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("VeiculoId");

                    b.ToTable("T_GATILHO_VIAGEM", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Viagens.Viagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VIA_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("VIA_ATIVO");

                    b.Property<string>("CodigoViagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VIA_CODIGO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VIA_CREATED_AT");

                    b.Property<DateTime?>("DataFimViagem")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VIA_DATA_FIM");

                    b.Property<DateTime?>("DataInicioViagem")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VIA_DATA_INICIO");

                    b.Property<DateTime>("DataViagem")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VIA_DATA");

                    b.Property<string>("DescricaoViagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VIA_DESCRICAO");

                    b.Property<decimal>("Distancia")
                        .HasColumnType("numeric")
                        .HasColumnName("VIA_DISTANCIA");

                    b.Property<decimal>("DistanciaRealizada")
                        .HasColumnType("numeric")
                        .HasColumnName("VIA_DISTANCIA_REALIZADA");

                    b.Property<bool>("Excesso")
                        .HasColumnType("boolean")
                        .HasColumnName("VIA_EXCESSO");

                    b.Property<long?>("GatilhoViagemId")
                        .HasColumnType("bigint")
                        .HasColumnName("GAT_ID");

                    b.Property<TimeSpan>("HorarioChegada")
                        .HasColumnType("interval")
                        .HasColumnName("VIA_HORA_CHEGADA");

                    b.Property<TimeSpan>("HorarioSaida")
                        .HasColumnType("interval")
                        .HasColumnName("VIA_HORA_SAIDA");

                    b.Property<decimal>("LatitudeFimViagem")
                        .HasColumnType("numeric")
                        .HasColumnName("VIA_LATITUDE_FIM");

                    b.Property<decimal>("LatitudeInicioViagem")
                        .HasColumnType("numeric")
                        .HasColumnName("VIA_LATITUDE_INICIO");

                    b.Property<long>("LocalidadeDestinoId")
                        .HasColumnType("bigint")
                        .HasColumnName("LOC_DESTINO_ID");

                    b.Property<long>("LocalidadeOrigemId")
                        .HasColumnType("bigint")
                        .HasColumnName("LOC_ORIGEM_ID");

                    b.Property<bool>("Lotado")
                        .HasColumnType("boolean")
                        .HasColumnName("VIA_LOTADO");

                    b.Property<string>("MotivoCancelamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VIA_MOTIVO_CANCELAMENTO");

                    b.Property<string>("MotivoProblema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VIA_MOTIVO_PROBLEMA");

                    b.Property<long>("MotoristaId")
                        .HasColumnType("bigint")
                        .HasColumnName("MOT_ID");

                    b.Property<int>("NumeroPassageiros")
                        .HasColumnType("integer")
                        .HasColumnName("VIA_NUMERO_PASSAGEIROS");

                    b.Property<string>("PolilinhaRota")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VIA_POLILINHA_ROTA");

                    b.Property<string>("PolilinhaRotaRealizada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VIA_POLILINHA_ROTA_REALIZADA");

                    b.Property<int>("QuantidadeVagas")
                        .HasColumnType("integer")
                        .HasColumnName("VIA_QUANTIDADE_VAGAS");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("VIA_SITUACAO");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VIA_UPDATED_AT");

                    b.Property<int>("VagasDisponiveis")
                        .HasColumnType("integer")
                        .HasColumnName("VIA_VAGAS_DISPONIVEIS");

                    b.Property<decimal>("ValorPassagem")
                        .HasColumnType("numeric")
                        .HasColumnName("VIA_VALOR_PASSAGEM");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("VEI_ID");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GatilhoViagemId");

                    b.HasIndex("LocalidadeDestinoId");

                    b.HasIndex("LocalidadeOrigemId");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("VeiculoId");

                    b.ToTable("T_VIAGEM", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Viagens.ViagemPassageiro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VIP_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VIP_CREATED_AT");

                    b.Property<long>("PassageiroId")
                        .HasColumnType("bigint")
                        .HasColumnName("PAS_PASSAGEIRO_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VIP_UPDATED_AT");

                    b.Property<long>("ViagemId")
                        .HasColumnType("bigint")
                        .HasColumnName("VIA_VIAGEM_ID");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PassageiroId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ViagemId");

                    b.ToTable("T_VIAGEM_PASSAGEIRO", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Viagens.ViagemPosicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VPO_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VPO_CREATED_AT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VPO_DATA_HORA");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VPO_LATITUDE");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VPO_LONGITUDE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VPO_UPDATED_AT");

                    b.Property<long>("ViagemId")
                        .HasColumnType("bigint")
                        .HasColumnName("VIA_ID");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ViagemId");

                    b.ToTable("T_VIAGEM_POSICAO", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Auditoria.HistoricoPropriedade", b =>
                {
                    b.HasOne("Dominio.Entidades.Auditoria.HistoricoObjeto", "HistoricoObjeto")
                        .WithMany("HistoricoPropriedade")
                        .HasForeignKey("HistoricoObjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricoObjeto");
                });

            modelBuilder.Entity("Dominio.Entidades.Pessoas.Passageiros.Passageiro", b =>
                {
                    b.HasOne("Dominio.Entidades.Localidades.Localidade", "LocalidadeDesembarque")
                        .WithMany()
                        .HasForeignKey("LocalidadeDesembarqueId");

                    b.HasOne("Dominio.Entidades.Localidades.Localidade", "LocalidadeEmbarque")
                        .WithMany()
                        .HasForeignKey("LocalidadeEmbarqueId");

                    b.HasOne("Dominio.Entidades.Localidades.Localidade", "Localidade")
                        .WithMany()
                        .HasForeignKey("LocalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidade");

                    b.Navigation("LocalidadeDesembarque");

                    b.Navigation("LocalidadeEmbarque");
                });

            modelBuilder.Entity("Dominio.Entidades.Veiculos.Veiculo", b =>
                {
                    b.HasOne("Dominio.Entidades.Veiculos.ModeloVeicular", "ModeloVeiculo")
                        .WithMany("Veiculos")
                        .HasForeignKey("ModeloVeiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModeloVeiculo");
                });

            modelBuilder.Entity("Dominio.Entidades.Viagens.Gatilho.GatilhoViagem", b =>
                {
                    b.HasOne("Dominio.Entidades.Localidades.Localidade", "LocalidadeDestino")
                        .WithMany()
                        .HasForeignKey("LocalidadeDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Localidades.Localidade", "LocalidadeOrigem")
                        .WithMany()
                        .HasForeignKey("LocalidadeOrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Veiculos.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalidadeDestino");

                    b.Navigation("LocalidadeOrigem");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Dominio.Entidades.Viagens.Viagem", b =>
                {
                    b.HasOne("Dominio.Entidades.Viagens.Gatilho.GatilhoViagem", "GatilhoViagem")
                        .WithMany("Viagens")
                        .HasForeignKey("GatilhoViagemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.Entidades.Localidades.Localidade", "LocalidadeDestino")
                        .WithMany()
                        .HasForeignKey("LocalidadeDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Localidades.Localidade", "LocalidadeOrigem")
                        .WithMany()
                        .HasForeignKey("LocalidadeOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Pessoas.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Veiculos.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GatilhoViagem");

                    b.Navigation("LocalidadeDestino");

                    b.Navigation("LocalidadeOrigem");

                    b.Navigation("Motorista");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Dominio.Entidades.Viagens.ViagemPassageiro", b =>
                {
                    b.HasOne("Dominio.Entidades.Pessoas.Passageiros.Passageiro", "Passageiro")
                        .WithMany()
                        .HasForeignKey("PassageiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Viagens.Viagem", "Viagem")
                        .WithMany()
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Passageiro");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("Dominio.Entidades.Viagens.ViagemPosicao", b =>
                {
                    b.HasOne("Dominio.Entidades.Viagens.Viagem", "Viagem")
                        .WithMany()
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("Dominio.Entidades.Auditoria.HistoricoObjeto", b =>
                {
                    b.Navigation("HistoricoPropriedade");
                });

            modelBuilder.Entity("Dominio.Entidades.Veiculos.ModeloVeicular", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("Dominio.Entidades.Viagens.Gatilho.GatilhoViagem", b =>
                {
                    b.Navigation("Viagens");
                });
#pragma warning restore 612, 618
        }
    }
}
