// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Data.Migrations
{
    [DbContext(typeof(RGRContext))]
    [Migration("20240817123825_RGR000004")]
    partial class RGR000004
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.Auditoria.HistoricoObjeto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Acao")
                        .HasColumnType("integer");

                    b.Property<long>("CodigoObjeto")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoAcao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescricaoObjeto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("OrigemAuditado")
                        .HasColumnType("integer");

                    b.Property<int>("TipoAuditado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HistoricoObjeto", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Auditoria.HistoricoPropriedade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("De")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("HistoricoObjetoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Para")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Propriedade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("HistoricoObjetoId");

                    b.ToTable("HistoricoPropriedade", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Veiculo.ModeloVeicular", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("integer");

                    b.Property<bool>("DescricaoModelo")
                        .HasColumnType("boolean");

                    b.Property<int>("PassageirosEmPe")
                        .HasColumnType("integer");

                    b.Property<bool>("PossuiBanheiro")
                        .HasColumnType("boolean");

                    b.Property<bool>("PossuiClimatizador")
                        .HasColumnType("boolean");

                    b.Property<int>("QuantidadeAssento")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeEixo")
                        .HasColumnType("integer");

                    b.Property<bool>("Situacao")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ModeloVeicular", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Veiculo.Veiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("integer");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaCNH")
                        .HasColumnType("integer");

                    b.Property<string>("Cor")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ModeloVeiculoId")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroChassi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCombustivel")
                        .HasColumnType("integer");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VencimentoLicenciamento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModeloVeiculoId");

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Auditoria.HistoricoPropriedade", b =>
                {
                    b.HasOne("Dominio.Entidades.Auditoria.HistoricoObjeto", "HistoricoObjeto")
                        .WithMany("HistoricoPropriedade")
                        .HasForeignKey("HistoricoObjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricoObjeto");
                });

            modelBuilder.Entity("Dominio.Entidades.Veiculo.Veiculo", b =>
                {
                    b.HasOne("Dominio.Entidades.Veiculo.ModeloVeicular", "ModeloVeiculo")
                        .WithMany("Veiculos")
                        .HasForeignKey("ModeloVeiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModeloVeiculo");
                });

            modelBuilder.Entity("Dominio.Entidades.Auditoria.HistoricoObjeto", b =>
                {
                    b.Navigation("HistoricoPropriedade");
                });

            modelBuilder.Entity("Dominio.Entidades.Veiculo.ModeloVeicular", b =>
                {
                    b.Navigation("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
