// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Data.Migrations.Cadastro
{
    [DbContext(typeof(CadastroContext))]
    partial class CadastroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.Localidades.Localidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LOC_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("LOC_ATIVO");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LOC_BAIRRO");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LOC_CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LOC_CIDADE");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LOC_COMPLEMENTO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LOC_CREATED_AT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LOC_UF");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("LOC_LATITUDE");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LOC_LOGRADOURO");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("LOC_LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LOC_NOME");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LOC_NUMERO");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LOC_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("T_LOCALIDADE", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Pessoas.Motorista", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MOT_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MOT_CNH");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MOT_CPF");

                    b.Property<int>("CategoriaCNH")
                        .HasColumnType("integer")
                        .HasColumnName("MOT_CATEGORIA_CNH");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MOT_CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MOT_EMAIL");

                    b.Property<long>("LocalidadeDesembarqueId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocalidadeEmbarqueId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocalidadeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MOT_NOME");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("MOT_OBSERVACAO");

                    b.Property<string>("RG")
                        .HasColumnType("text")
                        .HasColumnName("MOT_RG");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<bool>("Situacao")
                        .HasColumnType("boolean")
                        .HasColumnName("MOT_SITUACAO");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MOT_TELEFONE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MOT_UPDATED_AT");

                    b.Property<DateTime>("ValidadeCNH")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MOT_VALIDADE_CNH");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("T_MOTORISTA", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Pessoas.Passageiros.Passageiro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PAS_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PAS_CPF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAS_CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PAS_EMAIL");

                    b.Property<long?>("LocalidadeDesembarqueId")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("LOC_DESEMBARQUE_ID");

                    b.Property<long?>("LocalidadeEmbarqueId")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("LOC_EMBARQUE_ID");

                    b.Property<long>("LocalidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("LOC_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PAS_NOME");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PAS_OBSERVACAO");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("PAS_SEXO");

                    b.Property<bool>("Situacao")
                        .HasColumnType("boolean")
                        .HasColumnName("PAS_SITUACAO");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PAS_TELEFONE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAS_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LocalidadeDesembarqueId");

                    b.HasIndex("LocalidadeEmbarqueId");

                    b.HasIndex("LocalidadeId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("T_PASSAGEIRO", (string)null);
                });

            modelBuilder.Entity("Dominio.Entidades.Pessoas.Passageiros.Passageiro", b =>
                {
                    b.HasOne("Dominio.Entidades.Localidades.Localidade", "LocalidadeDesembarque")
                        .WithMany()
                        .HasForeignKey("LocalidadeDesembarqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Localidades.Localidade", "LocalidadeEmbarque")
                        .WithMany()
                        .HasForeignKey("LocalidadeEmbarqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Localidades.Localidade", "Localidade")
                        .WithMany()
                        .HasForeignKey("LocalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidade");

                    b.Navigation("LocalidadeDesembarque");

                    b.Navigation("LocalidadeEmbarque");
                });
#pragma warning restore 612, 618
        }
    }
}
